### ISSUE TITLE
DeclareProperty malfunction for LiveListeners

### ISSUE THREAD

**Issue by LamarMoore** [ScreamingUdder/mantid#11]
I encountered a strange bug when trying to declare a bool property for the ISISKafkaEventListener. It seems as though all declared properties are treated as text entries. Even when explicitly declared as boolean properties using `PropertyWithValue<bool>`. If the user enters text in the text box provided, the input is rejected and the user is prompted to enter a value compatible with a boolean value. So although the property is expected to be a boolean, a text box is provided to capture the info.

This occurs [here](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomDialogs/src/StartLiveDataDialog.cpp#L468) where all listener properties are represented by `QLineEdit` instead of calling `PropertyWidgetFactory`

**Comment by matthew-d-jones** [comment]
@LamarMoore I think this issue and the fix should be in mantidproject/mantid as it is more general than the Kafka listener.

**Comment by LamarMoore** [comment]
This has been created as an issue in the main mantid repo [here](https://github.com/mantidproject/mantid/issues/18448)
