### ISSUE TITLE
OSX packaging fixes

### ISSUE THREAD

**Issue by OwenArnold** [ScreamingUdder/mantid#19]
Patches to get drag and drop installer working for the mac against `isis_kafka_listener` branch. Patch file is attached. This correctly generates the package that seems to work against the `mdj` producer as tested via `StartLiveData`.

Side points to note:

1. Despite using the isis kafka event listener. `Workspace2D` are produced by `StartLiveData` (no processing applied). Not sure why that should be?
1. Building that branch raised some warnings that should be fixed.
![screen shot 2017-01-20 at 08 53 15](https://cloud.githubusercontent.com/assets/1109536/22143529/3ed502da-def2-11e6-9e17-5c13ac01ac22.png)

**Comment by OwenArnold** [comment]
[0001-package-kafka-libraries.txt](https://github.com/ScreamingUdder/mantid/files/718928/0001-package-kafka-libraries.txt)

**Comment by matthew-d-jones** [comment]
To answer point 1. a `Workspace2D` is created if `Preserve Events` is not selected.
